# Generated by Django 3.2.6 on 2021-08-26 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcclinic', '0002_auto_20210826_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(default='Текст статьи'),
        ),
    ]
