# Generated by Django 3.2.6 on 2021-08-26 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcclinic', '0003_auto_20210826_1822'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
    ]
